### ISSUE TITLE
ETA on full v5.3 support?

### ISSUE THREAD

**Issue by infosec-shinobi** [appgate/sdp-api-client-go#2]
Hey guys, 

Any eta on when v5.3 will be fully supported? Will v13 fully support v5.3, or are you releasing v14 soon?

**Comment by danijeel** [comment]
we are working on full 5.3 support by the end of Q1. The current version works against 5.3 but does not included new attributes that has been introduced in the new version.

**Comment by infosec-shinobi** [comment]
Thank you!
