### ISSUE TITLE
New tagged versions?

### ISSUE THREAD

**Issue by noxoraAtWork** [appgate/sdp-api-client-go#21]
Hi there! I noticed y'all have a good compatibility matrix and have versions extending from v12 to v18, but the most recent tagged version only includes api versions from v12 to v16. Would it be possible to add a newer tagged version which includes all api versions?

**Comment by danijeel** [comment]
Hi @noxoraAtWork , I created a tag [v1.1.0](https://github.com/appgate/sdp-api-client-go/releases/tag/v1.1.0) now and I will resume using semver releases in upcoming changes. Internally we have used git SHA to track changes, but we can switch to git tags.
