### ISSUE TITLE
v13 OpenAPI LicenseUsersDistinguishedNameDelete 

### ISSUE THREAD

**Issue by joshhuie** [appgate/sdp-api-client-go#3]
Hello! I've encountered an error when executing a `LicenseUsersDistinguishedNameDelete`  in `api_licensed_users.go`. I get a `404 Not Found` error when passing a correctly formatted distinguished name to this function. I suspect the query is being URL encoded incorrectly.

**Comment by danijeel** [comment]
hey @joshhuie , I've not been able to reproduce this, you can see my test here https://gist.github.com/danijeel/cf11720e432216b426bdf3fe22710d20

tested with **5.2.2-22233-release** using v13 and **5.3.2-23587-release** using v13

What version on the appliances are you using?

**Comment by stephengroat** [comment]
👋  currently using `5.2.3-22549-release (c)`

**Comment by joshhuie** [comment]
> 👋 currently using `5.2.3-22549-release (c)`

@danijeel

**Comment by danijeel** [comment]
I cant see any major diff between the two minor versions that would affect this, Do you get the same error from the gist above with your given input? 
btw, i can give you an head's up that in 5.4 this endpoint has been removed.

**Comment by stephengroat** [comment]
@danijeel what endpoint is replacing it? we rely on this for critical functionality

**Comment by joshhuie** [comment]
> I cant see any major diff between the two minor versions that would affect this, Do you get the same error from the [gist](https://gist.github.com/danijeel/cf11720e432216b426bdf3fe22710d20) above with your given input?

Yup, I still get a `error 404 Not Found`. The encoded URL shows up as this `DELETE /admin/license/users/CN%3Dexample%40testing.email%2COU%3DLogin+With+Google HTTP/1.1` for this distinguished name: `Delete DN "CN=example@testing.email,OU=Login With Google"
`

**Comment by gokhan-berberoglu** [comment]
@joshhuie thanks for the info, we're investigating.

@stephengroat 
> @danijeel what endpoint is replacing it? we rely on this for critical functionality

Appgate SDP introduces changes to licensing with v5.4. Starting with v5.4, Controller automatically cleans up the inactive user licenses after lease period, 30 days. It will not be possible to delete assigned licenses manually, so rest api is dropped. If you contact Support with information on why deleting license assigment via rest api is critical for your, we can discuss various options.

**Comment by danijeel** [comment]
After digging through the changelog in the openapi-generator, we can see that this [issue](https://github.com/OpenAPITools/openapi-generator/pull/6618) has been resolved upstream, I'll see if I can generate a new one. This proberbly affect all versions.

**Comment by danijeel** [comment]
This is fixed in 1.0.1 https://github.com/appgate/sdp-api-client-go/releases/tag/v1.0.1, this includes v13 re-generated with openapitools/openapi-generator:cli-v5.1.0 that resolves this issue with url encoding.
